name: product-storage

services:
  backend-service:
    build: ./
    command: ./backend-service
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env

  postgres_db:
    image: postgres:16-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env